@baseUrl = https://8080-davidmarqss-apitarefaja-awpweyi1tp0.ws-us116.gitpod.io
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgVGFyZWZhcyIsInN1YiI6InVzZXIiLCJleHAiOjE3MjU0MDI5OTJ9.aV1BJKAOpErVzTGGwl_C5FXUuvJ5fYxrfZUYj9qiTeA


###
GET {{baseUrl}}/tarefas
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/tarefas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao": "Criar Formulári@o",
    "concluido": false
}

###
GET {{baseUrl}}/tarefas/4
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/tarefas/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "descricao": "Testando Alteração",
    "concluido": false
}

###
DELETE {{baseUrl}}/tarefas/1
Authorization: Bearer {{token}}